export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  library: '/library',
  research: '/research',
  customization: '/customization',
  journal: '/journal',
  settings: '/settings',
  knowledge: (slug: string) => `/library/knowledge/${slug}`,
  knowledgeEdit: (slug: string) => `/library/knowledge/${slug}/edit`,
  source: (id: string) => `/library/source/${id}`,
  sourceEdit: (id: string) => `/library/source/${id}/edit`,
  note: (id: string) => `/library/note/${id}`,
} as const
