export function getIngestPrompt(params: {
  originalName: string
  uploadedType: string
  fileKind: string
  rawStorageUrl: string
  candidates: any[]
  extractedText: string
}): string {
  const { originalName, uploadedType, fileKind, rawStorageUrl, candidates, extractedText } = params
  return `You are extracting durable knowledge from a user's Source of Truth.
The backend has already converted the uploaded file to plain text. Use only the text below. Do not assume access to the original file bytes.

Return ONLY valid JSON in this shape:
{
  "summary": {
    "category": "Short category",
    "tags": ["tag-one"],
    "excerpt": "Short descriptive summary of the source as a whole. Strictly limited to at most 4 sentences.",
    "body": "# Clean Source Title\\n\\nA concise source-level summary in markdown..."
  },
  "pages": [
    {
      "action": "create | update | merge | replace | link_only | skip",
      "targetSlug": "existing-slug-when-updating-merging-replacing-or-linking",
      "filename": "page-slug.md",
      "title": "Knowledge page title",
      "overview": "Short descriptive overview of this knowledge page. Strictly limited to at most 4 sentences.",
      "body": "# Knowledge Page Title\\n\\nA self-contained markdown article extracted from the source text...",
      "related": ["Related concept"],
      "reason": "Short reason for the action"
    }
  ]
}

Rules:
- Return plain JSON only. No markdown code fences.
- Keep every claim grounded in the extracted text.
- Treat the source as Source of Truth and the pages as extracted Knowledge. Knowledge pages should read like standalone notes derived from the source, not copied fragments of the original file.
- For "summary.body", write a source-level summary only. Do not duplicate the same title and summary twice. Do not reproduce the full original outline unless it is genuinely necessary.
- For each page "body", start with exactly one H1 that matches the page title. Do not begin with a copied source heading like "# 5. Topic" unless the number is an essential name.
- Remove or normalize inherited section numbering from the original source. If the source has headings "3.", "4.", "5.", the extracted knowledge page must not suddenly start at "5."; use clean headings or renumber local steps from 1.
- Preserve useful Markdown structure when the uploaded file is Markdown, but clean it into a readable knowledge article.
- The "excerpt" under "summary" must be a brief source-level summary, generated by you, limited to at most 4 sentences. Do not truncate by characters.
- The "overview" under each page in "pages" must be a brief summary of that knowledge page's content, generated by you, limited to at most 4 sentences. Do not truncate by characters.
- Decide whether each useful concept should create a new page, update an existing page, merge into an existing page, replace an existing page, only add provenance, or be skipped.
- Use "update" when a candidate Knowledge Entry already covers the concept but needs new details.
- Use "merge" when the new source overlaps with an existing candidate and the best result is one canonical Knowledge page that combines both old and new material.
- Use "replace" when an existing candidate is about the same concept but the new source is a clearer or more authoritative version, so the Knowledge page should be rewritten from this source while keeping provenance.
- Use "link_only" when the source supports an existing entry but does not require Markdown changes.
- Use "skip" when the source has no durable knowledge contribution.
- For "update", "merge", "replace", and "link_only", always set "targetSlug" to the existing Knowledge Entry slug.
- For every non-create action, make "reason" specific enough to show in the Knowledge page timeline, e.g. what was merged, replaced, or linked and why.
- Put concept/topic tags in "tags".
- Return only the fields in the JSON shape above. This app currently uses only category and concept/topic tags for labeling.
- Use "related" only for other durable knowledge concepts that would make useful sidebar links. Do not use it for source sections, citations, or generic terms.

File metadata:
- Original filename: ${originalName}
- Uploaded source type: ${uploadedType}
- Extracted file kind: ${fileKind}
- Raw storage URL: ${rawStorageUrl}

Existing candidate Knowledge Entries:
${JSON.stringify(candidates, null, 2)}

Extracted text:
${extractedText}`
}
