export function getIngestSummaryPrompt(params: {
  originalName: string
  uploadedType: string
  fileKind: string
  extractedText: string
}): string {
  const { originalName, uploadedType, fileKind, extractedText } = params
  return `You are extracting durable knowledge from a user's Source of Truth.
The backend has already converted the uploaded file to plain text. Use only the text below. Do not assume access to the original file bytes.

Return ONLY valid JSON in this shape:
{
  "summary": {
    "category": "Short category",
    "tags": ["tag-one"],
    "excerpt": "Short descriptive summary of the source as a whole. Strictly limited to at most 4 sentences.",
    "body": "# Clean Source Title\\n\\nA concise source-level summary in markdown..."
  }
}

Rules:
- Return plain JSON only. No markdown code fences.
- Keep every claim grounded in the extracted text.
- Treat the source as Source of Truth.
- For "summary.body", write a source-level summary only. Do not reproduce the full original outline unless it is genuinely necessary.
- The "excerpt" under "summary" must be a brief source-level summary, generated by you, limited to at most 4 sentences. Do not truncate by characters.
- Put concept/topic tags in "tags".

File metadata:
- Original filename: ${originalName}
- Uploaded source type: ${uploadedType}
- Extracted file kind: ${fileKind}

Extracted text:
${extractedText}`
}
